all:
  hosts:
    dev-web1:
      ansible_host: 192.168.1.10
      ansible_user: devuser
    dev-web2:
      ansible_host: 192.168.1.11
      ansible_user: devuser
    dev-db1:
      ansible_host: 192.168.1.20
      ansible_user: devuser
  children:
    webservers:
      hosts:
        dev-web1:
        dev-web2:
    dbservers:
      hosts:
        dev-db1:
